import { FortuneCategory } from '@Apps/terminal/commands/fortune/fortune.types';

const fortuneCategories: Record<FortuneCategory, string[]> = {
  [FortuneCategory.Programming]: [
    "You will write bug-free code today.",
    "The next commit will fix everything.",
    "You will discover a forgotten feature that solves your problem.",
    "Today is a good day to refactor.",
    "Don't deploy on Friday.",
    "Your coffee will not go cold before the build finishes.",
    "The prod server will survive the night.",
    "You will finally understand that regex.",
    "A long-standing bug will fix itself. Somehow.",
    "Someone will praise your naming conventions.",
    "You will remember to write tests before pushing.",
    "The CI pipeline will pass on the first try.",
    "Your StackOverflow question will be answered immediately.",
    "The docs will be surprisingly helpful today.",
    "Your code will compile without warnings.",
    "You will resist the urge to add just one more feature.",
    "A mysterious log will finally make sense.",
    "You will not forget a semicolon today.",
    "You will finally remove that TODO from 2020.",
    "You will actually understand someone else's code.",
    "A merge conflict will resolve itself peacefully.",
    "Your rubber duck will be extra insightful today.",
    "The user will actually read the error message.",
    "Your boss will say 'Take your time' and mean it.",
    "Your dev environment will stop acting weird.",
    "You will finish a ticket faster than expected.",
    "A deprecated method will lead you to a better solution.",
    "You will close more tabs than you open today.",
    "You will explain something complex clearly and simply.",
    "The code review will be kind and constructive."
  ],
  [FortuneCategory.Productivity]: [
    "Your branch name will make someone smile.",
    "You will find a comment that explains everything perfectly.",
    "Today, you will refactor without regrets.",
    "You will finally learn what that one setting does.",
    "Autocomplete will save you again.",
    "The build will be fast and furious.",
    "You will write a meaningful commit message.",
    "You will not push to the wrong branch.",
    "You will write the best function of your week today.",
    "You will discover a shortcut that changes your workflow.",
    "Your terminal will behave exactly as expected.",
    "You will resist the temptation to overengineer.",
    "Someone will thank you for that one-line fix.",
    "You'll remember to hydrate and stretch.",
    "You'll take a break right when you need it.",
    "An old snippet will save your day.",
    "The API will return what you expect — the first time.",
    "You'll debug in record time.",
    "Your linter will find nothing to complain about.",
    "The meeting will be cancelled and no one will reschedule."
  ],
  [FortuneCategory.Debugging]: [
    "Someone will understand your joke in the code comments.",
    "Your app won't crash during the demo.",
    "You'll write a test that catches a real bug.",
    "Your laptop fan will stay quiet all day.",
    "You will not Google the same error for the third time.",
    "Your dark theme will protect your soul.",
    "Today, legacy code will welcome your touch.",
    "Your pseudocode will run perfectly in your mind.",
    "You will finally delete that unnecessary file.",
    "A comment from the past will save your future.",
    "You will find joy in solving a small problem.",
    "You will say 'just one more fix' — and it *will* be one.",
    "You'll find a library that does *exactly* what you need.",
    "A 5-minute fix will actually take 5 minutes.",
    "You will avoid yak shaving entirely.",
    "Your code will work in all browsers — even Safari."
  ],
  [FortuneCategory.Workflow]: [
    "You will finally remove that console.log.",
    "You will remember to update the documentation.",
    "You will feel proud of your git history.",
    "You'll resist pushing broken code 'just to test in staging'.",
    "You'll notice a typo before you hit send.",
    "You will close Jira with satisfaction.",
    "You'll teach someone something useful today.",
    "Your design will look better than the mockup.",
    "You'll finally clean up your desktop.",
    "The terminal will autocomplete the right file.",
    "Your keyboard will feel especially clicky today.",
    "You will befriend an unfamiliar tool.",
    "You'll upgrade a package and nothing will break.",
    "You'll find a helpful log buried deep in the output.",
    "Your Slack will stay quiet while you're in flow.",
    "You'll rename that variable — and it will finally make sense."
  ],
  [FortuneCategory.Success]: [
    "You will understand what the error is really saying.",
    "Someone will say 'nice solution' and mean it.",
    "You'll get to the bottom of that flaky test.",
    "You'll manage to work without distractions.",
    "Today, your tabs will be organized chaos — and it will work.",
    "The 'quick fix' will not become tech debt.",
    "You will remember to use `git stash` wisely.",
    "Your local server will not mysteriously crash today.",
    "You'll read the changelog *before* updating.",
    "Someone will fix a bug you didn't know you had.",
    "Your feature will behave exactly as you imagined.",
    "You'll make time for a little code cleanup.",
    "Your imports will all resolve on the first try.",
    "Your build will pass — even on the first try on CI.",
    "The keyboard gods will bless your shortcuts today.",
    "You will finally commit with confidence.",
    "Your localStorage will not mysteriously reset.",
    "You'll finally remove that last `any` from your types.",
    "Your deployment will feel like a mic drop.",
    "You'll find joy in the smallest refactor.",
    "Your code won't just work — it'll shine."
  ],
  [FortuneCategory.Wisdom]: [
    "Programs must be written for people to read, and only incidentally for machines to execute.",
    "The best code is no code at all.",
    "Premature optimization is the root of all evil.",
    "There are only two hard things in Computer Science: cache invalidation and naming things.",
    "Code is like humor. When you have to explain it, it's bad.",
    "First, solve the problem. Then, write the code.",
    "The most important property of a program is whether it accomplishes the intention of its user.",
    "Programming is thinking, not typing.",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.",
    "The only way to go fast, is to go well."
  ],
  [FortuneCategory.Motivational]: [
    "Every expert was once a beginner.",
    "Progress over perfection.",
    "Your potential is endless.",
    "Today's struggles are tomorrow's strengths.",
    "Believe in your ability to figure things out.",
    "Small steps lead to big changes.",
    "You are capable of amazing things.",
    "Growth happens outside your comfort zone.",
    "Your creativity knows no bounds.",
    "Trust the process, trust yourself."
  ],
  [FortuneCategory.All]: [],
};

export { fortuneCategories };
