import { DialogueNode } from '../useDialogue';

export const welcomeFirstVisit: DialogueNode[] = [
  {
    id: 'fox_greeting',
    speaker: 'fox',
    position: 'left',
    text: 'Эй, привет! Ты первый раз здесь?',
    emotion: 'excited',
    autoNext: null,
    next: 'fox_introduce',
  },
  {
    id: 'fox_introduce',
    speaker: 'fox',
    position: 'left',
    text: 'Я Fox. Помогаю тут разбираться с системой. ZakulisaOS — это веб-операционка, работает прямо в браузере.',
    autoNext: null,
    next: 'vixie_appears',
  },
  {
    id: 'vixie_appears',
    speaker: 'vixie',
    position: 'right',
    text: 'И снова новенький.',
    emotion: 'tired',
    autoNext: 2500,
    next: 'fox_reaction',
  },
  {
    id: 'fox_reaction',
    speaker: 'fox',
    position: 'left',
    text: 'Это Vixie. Не обращай внимания на её тон.',
    emotion: 'neutral',
    autoNext: null,
    next: 'vixie_irony',
  },
  {
    id: 'vixie_irony',
    speaker: 'vixie',
    position: 'right',
    text: 'Просто я не притворяюсь, что рада каждому юзеру.',
    emotion: 'ironic',
    autoNext: 2500,
    next: 'fox_choice',
  },
  {
    id: 'fox_choice',
    speaker: 'fox',
    position: 'left',
    text: 'Ладно, давай по делу. Хочешь создать аккаунт или просто посмотреть, что тут есть?',
    emotion: 'neutral',
    choices: [
      { text: 'Создать аккаунт', next: 'choice_register' },
      { text: 'Зайти как гость', next: 'choice_guest' },
      { text: 'Войти в существующий', next: 'choice_login' },
    ],
  },
  {
    id: 'choice_register',
    speaker: 'fox',
    position: 'left',
    text: 'Отлично, сейчас откроем форму регистрации.',
    emotion: 'excited',
    autoNext: 1500,
  },
  {
    id: 'choice_guest',
    speaker: 'vixie',
    position: 'right',
    text: 'Разумный выбор. Сначала посмотри, потом решишь.',
    emotion: 'neutral',
    autoNext: 1500,
  },
  {
    id: 'choice_login',
    speaker: 'fox',
    position: 'left',
    text: 'Понял, переходим на страницу входа.',
    emotion: 'neutral',
    autoNext: 1500,
  },
];

export const welcomeReturningVisit = (username: string): DialogueNode[] => [
  {
    id: 'fox_welcome_back',
    speaker: 'fox',
    position: 'left',
    text: `${username}, ты вернулся! Как дела?`,
    emotion: 'excited',
    autoNext: null,
    next: 'vixie_notices',
  },
  {
    id: 'vixie_notices',
    speaker: 'vixie',
    position: 'right',
    text: 'А, это ты. Опять.',
    emotion: 'tired',
    autoNext: 2000,
    next: 'fox_encourages',
  },
  {
    id: 'fox_encourages',
    speaker: 'fox',
    position: 'left',
    text: 'Ну всё, готов продолжить?',
    emotion: 'neutral',
    autoNext: 2000,
  },
];