const ACHIEVEMENT_DIR = '/achievements';
const ACHIEVEMENT_PROGRESS_FILE = 'progress.json';
const ACHIEVEMENT_STATS_FILE = 'stats.json';
const ACHIEVEMENT_BACKUP_DIR = 'backups';
const ACHIEVEMENT_MAX_BACKUPS = 10;

export { ACHIEVEMENT_DIR, ACHIEVEMENT_BACKUP_DIR, ACHIEVEMENT_STATS_FILE, ACHIEVEMENT_PROGRESS_FILE, ACHIEVEMENT_MAX_BACKUPS };
