import { initEchoCommand } from '@Apps/terminal/commands/echo/echo.terminal-command';
import { initWhoamiCommand } from '@Apps/terminal/commands/whoami/whoami.terminal-command';
import { initVersionCommand } from '@Apps/terminal/commands/version/version.terminal-command';
import { initClearCommand } from '@Apps/terminal/commands/clear/clear.terminal-command';
import { initAliasCommand } from '@Apps/terminal/commands/alias/alias.command-terminal';
import { init42Command } from '@Apps/terminal/commands/42/42.terminal-command';
import { initCreditsCommand } from '@Apps/terminal/commands/credits/credits.terminal-command';
import { initHackCommand } from '@Apps/terminal/commands/hack/hack.terminal-command';
import { initHelpCommand } from '@Apps/terminal/commands/help/help.terminal-command';
import { initNextCommand } from '@Apps/terminal/commands/next/next.terminal-command';
import { initUuidCommand } from '@Apps/terminal/commands/uuid/uuid.terminal-command';
import { initFortuneCommand } from '@Apps/terminal/commands/fortune/fortune.terminal-command';
import { initJokeCommand } from '@Apps/terminal/commands/joke';
import { init8BallCommand } from '@Apps/terminal/commands/8ball/8Ball.terminal-command';
import { initAsciiCommand } from '@Apps/terminal/commands/ascii/ascii.terminal-command';
import { initCowsayCommand } from '@Apps/terminal/commands/cowsay/cowsay.terminal-command';
import { initMatrixCommand } from '@Apps/terminal/commands/matrix/matrix.terminal-command';
import { initRandomCommand } from '@Apps/terminal/commands/random/random.terminal-command';
import { initDateCommand } from '@Apps/terminal/commands/date/date.terminal-command';
import { initFlipCommand } from '@Apps/terminal/commands/flip/flip.terminal-command';
import { initRollCommand } from '@Apps/terminal/commands/roll/roll.terminal-command';
import { initDecode64Command } from '@Apps/terminal/commands/decode64/decode64.terminal-command';
import { initEncode64Command } from '@Apps/terminal/commands/encode64/encode64.terminal-command';
import { initHelloCommand } from '@Apps/terminal/commands/hello/hello.terminal-command';
import { initUptimeCommand } from '@Apps/terminal/commands/uptime/uptime.terminal-command';
import { initWhenCommand } from '@Apps/terminal/commands/when/when.terminal-command';
import { initGrepCommand } from '@Apps/terminal/commands/grep/grep.terminal-command';
import { initWcCommand } from '@Apps/terminal/commands/wc/wc.terminal-command';
import { initSleepCommand } from '@Apps/terminal/commands/sleep/sleep.terminal-command';
import { initLsCommand } from '@Apps/terminal/commands/fs';
import { initCdCommand } from '@Apps/terminal/commands/fs/cd.terminal-command';
import { initPwdCommand } from '@Apps/terminal/commands/fs/pwd.terminal-command';
import { initCatCommand } from '@Apps/terminal/commands/fs/cat.terminal-command';
import { initMkdirCommand } from '@Apps/terminal/commands/fs/mkdir.terminal-command';
import { initRmCommand } from '@Apps/terminal/commands/fs/rm.terminal-command';
import { initMvCommand } from '@Apps/terminal/commands/fs/mv.terminal-command';
import { initCpCommand } from '@Apps/terminal/commands/fs/cp.terminal-command';
import { initTouchCommand } from '@Apps/terminal/commands/fs/touch.terminal-command';
import { initSlCommand } from '@Apps/terminal/commands/sl/sl.terminal-command';
import { initAchievementsCommand } from '@Apps/terminal/commands/achievement/achievement.terminal-command';
import { initSortCommand } from '@Apps/terminal/commands/sort/sort.terminal-command';
import { initFindCommand } from '@Apps/terminal/commands/find/find.terminal-command';
import { AchievementAPI, FileSystemAPI, TerminalAPI } from '@nameless-os/sdk';
import { initRunCommand } from '@Apps/terminal/commands/run';

function initBasicTerminalCommands(terminalApi: TerminalAPI, fileSystem: FileSystemAPI, achievementApi: AchievementAPI) {
  initEchoCommand(terminalApi);
  initWhoamiCommand(terminalApi);
  initVersionCommand(terminalApi);
  initClearCommand(terminalApi);
  initAliasCommand(terminalApi);
  init42Command(terminalApi);
  initCreditsCommand(terminalApi);
  initHackCommand(terminalApi)
  initHelpCommand(terminalApi);
  initNextCommand(terminalApi);
  initUuidCommand(terminalApi);
  initFortuneCommand(terminalApi);
  initJokeCommand(terminalApi);
  init8BallCommand(terminalApi);
  initAsciiCommand(terminalApi);
  initCowsayCommand(terminalApi);
  initMatrixCommand(terminalApi);
  initRandomCommand(terminalApi);
  initDateCommand(terminalApi);
  initFlipCommand(terminalApi);
  initRollCommand(terminalApi);
  initDecode64Command(terminalApi);
  initEncode64Command(terminalApi);
  initHelloCommand(terminalApi);
  initUptimeCommand(terminalApi);
  initWhenCommand(terminalApi);
  initGrepCommand(terminalApi);
  initWcCommand(terminalApi);
  initSleepCommand(terminalApi);
  initLsCommand(terminalApi, fileSystem);
  initCdCommand(terminalApi, fileSystem);
  initPwdCommand(terminalApi);
  initCatCommand(terminalApi, fileSystem);
  initMkdirCommand(terminalApi, fileSystem);
  initRmCommand(terminalApi, fileSystem);
  initMvCommand(terminalApi, fileSystem);
  initCpCommand(terminalApi, fileSystem);
  initTouchCommand(terminalApi, fileSystem);
  initSlCommand(terminalApi);
  initAchievementsCommand(terminalApi, achievementApi);
  initSortCommand(terminalApi);
  initFindCommand(terminalApi, fileSystem);
  initRunCommand(terminalApi, fileSystem);
}

export { initBasicTerminalCommands };